### ISSUE TITLE
Where to find the article

### ISSUE THREAD

**Issue by WindVChen** [rockeyben/DCCF#1]
Hi,

I'm curious about this direction. Would you mind sharing your paper, as I fail to find it online.

Looking forward to your help, thanks.

**Comment by chenquan-cq** [comment]
Arxiv version: https://arxiv.org/abs/2207.04788

**Comment by rockeyben** [comment]
This repo is still updating, we have put the arxiv link [https://arxiv.org/abs/2207.04788](https://arxiv.org/abs/2207.04788) in the latest readme version.
