### ISSUE TITLE
Can't download a pretrained model

### ISSUE THREAD

**Issue by tamlog06** [rockeyben/DCCF#2]
Could you please upload the pretrained model to Google drive or Drop box, not BaidoCloud?

**Comment by rockeyben** [comment]
ok, I will upload them to google drive very soon.

**Comment by rockeyben** [comment]
The google drive link is now updated in README. Closing this issue.

[Google Drive Link](https://drive.google.com/drive/folders/1RFuf2zMU55ISYWSqu6HDELSxZTne8_u_?usp=sharing)
