### ISSUE TITLE
About the reproduction of the evaluation on the Raw size iHarmony dataset.

### ISSUE THREAD

**Issue by WindVChen** [rockeyben/DCCF#3]
Hello there,

It is a nice work. However, when I try to reproduce the results on the Raw size iHarmony dataset, I encounter lower performance than the paper. Specifically, I use the provided pretrained model ```dccf_idih_HR_pretrain.pth```, and run the following code:
```
python scripts/evaluate_upsample_refiner.py dccf_improved_dih256_HR_clamp pretrained_models/dccf_idih_HR_pretrain.pth \
    --resize-strategy None\
    --version hsl_nobb \
    --config-path config_test_HR.yml 
```
However, the evaluation results are as follows:
![image](https://user-images.githubusercontent.com/56162412/196878794-5826834a-7982-4902-a655-0a3f30f81000.png)

which is very different from the results shown in paper:
![image](https://user-images.githubusercontent.com/56162412/196878930-5cc6628b-91df-4c2a-a5c5-0c7553774ff3.png)

Could you help me how to get the correct evaluations?

**Comment by rockeyben** [comment]
The results in this table was evaluated from this script, using the pretrained model with hrnet backbone. Hope it can help you. :D

```shell
pretrain_path="pretrained_models/dccf_idih_hrnet18s_v2p_HR_pretrain.pth"
CUDA_VISIBLE_DEVICES=0 python3 scripts/evaluate_upsample_refiner.py hrnet18s_v2p_idih256_upsample_hsl_refine_HR ${pretrain_path} \
    --resize-strategy Fixed256 \
    --version hsl \
    --config-path config_test_HR.yml 
```

**Comment by WindVChen** [comment]
@rockeyben Thanks for your reply. It does work. 

There is one thing I would like to confirm is that the final DCCF is based on the pyramid version of iDIH-HRNet, while the "DIH" in Table 1, Supplement corresponds to the iDIH-HRNet without pyramid, as I found the results above are the same as that in Table 1.

Hope for your help, thanks.

**Comment by rockeyben** [comment]
Yes, currently the best model in main paper was based on the pyramid version. The experiments in supplementary only aimed at confirming DCCF can match different backbones.

**Comment by WindVChen** [comment]
I see. Thanks.
