### ISSUE TITLE
About citation format.

### ISSUE THREAD

**Issue by WindVChen** [rockeyben/DCCF#4]
Hi there,

I want to cite this paper in my work. However, I can only find the Arxiv citation format online, but fail to find the ECCV citation format. 

Could you help me if there is the ECCV citation format?

**Comment by rockeyben** [comment]
Thanks for citing our work.
I have just updated the citation format in the ending of README.
Wish it's not too late for your DDL. :D

**Comment by WindVChen** [comment]
Thanks. Just in time :)
